#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  Yonas-frontend
        bind *:80
        mode http
        default_backend Yonas-backend
backend Yonas-backend
        balance roundrobin
        server 89996-web-01 54.157.159.167 check
        server 89996-web-02 54.152.96.111 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
