#!/bin/bash
mkdir welcome/welcome/to/welcome/to/school
mkdir -p
mkdir -p welcome/to/ welcome/ welcome/to/school
mkdir {welcome/,welcome/to/,welcome/to/school}
mkdir welcome/,welcome/to/,welcome/to/school
